version: "3.8"
services: 
    dev:
        image: node:14
        environment: 
            - PORT=8080
        working_dir: /usr/src/app
        volumes:
            - type: bind
              source: ./
              target: /usr/src/app
            - type: volume
              source: nodemodules # name of the volume, see below
              target: /usr/src/app/node_modules
              volume:
                nocopy: true
        command: >
                sh -c "npm install -g nodemon &&
                       npm install &&
                       npm run dev"
        ports: 
            - "8080:8080"
volumes: 
    nodemodules: