version: "3"
services: 
    express:
        image: node:14
        environment: 
            - PORT=8080
        volumes:
            - type: bind
              source: ./
              target: /usr/src/app
            - type: volume
              source: nodemodules # name of the volume, see below
              target: /usr/src/app/node_modules
              volume:
                nocopy: true
        working_dir: /usr/src/app
        # command: npm run dev
        ports: 
            - "8080:8080"
volumes: 
    nodemodules: