version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app/server
      - type: bind
        source: ./
        target: /usr/src/app/client
      - type: volume
        source: nodemodules # name of the volume, see below
        target: /usr/src/app/node_modules
        volume:
          nocopy: true
    # command: >
    #   sh -c "npm install -g nodemon &&
    #          npm install &&
    #          npm run dev"
    ports:
      - "8080:8080"
volumes:
  nodemodules:
